### ISSUE TITLE
Not compatible with version 8.3.0

### ISSUE THREAD

**Issue by ChrisSka** [Kharg/email-filters#1]
A great extension, but since the update to version 8.3.0 it no longer works and you get error 500

![image](https://github.com/Kharg/email-filters/assets/68166740/c44a0405-4c08-412a-bb27-7cc9a0bf5a43)
![image](https://github.com/Kharg/email-filters/assets/68166740/d9cde762-e65d-40db-baf8-c94314015d7f)

**Comment by ChrisSka** [comment]
Hy Kharg,
Are you planning to correct the error?

**Comment by Kharg** [comment]
@ChrisSka I am looking for a possible fix :(

**Comment by Kharg** [comment]
@ChrisSka I was able to fix the issue. Update coming soon :)

**Comment by Kharg** [comment]
1.1.0 adds compatibility with Espo 8.3.0+
https://github.com/Kharg/email-filters/releases/tag/1.1.0
